<?php

use Illuminate\Database\Seeder;

class Orders extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('orders')->delete();
        DB::table('orders')->insert([
            ['id' => 1, 'user_id_receiver' => 2, 'user_id' => 2, 'code_deal' => '1000000000000', 'sell_buy' => 1, 'money_value' => 10000000, 'cotpay_fee' => 100000, 'content' => 'Đồng hồ', 'wallet_id' => 5, 'phone_receiver' => '0987654322', 'name_sender' => 'Nguyễn thị Chi', 'name_user' => 'Gia dụng shop', 'name_receiver' => 'Nguyễn thị chi', 'address_receiver' => '18 trúc bạch', 'city' => 'Hà Nội', 'district' => 'Sơn Tây', 'ward' =>'Sơn Đông', 'shipping_unit' => 1, 'wide' =>10, 'long' => 10, 'height' => 10, 'collection' =>1, 'service' => 1, 'weight' => 50, 'ship_fee' => 10000, 'status' => 1,'code_bill'=>'-','date_ship_receive'=>'2020-04-13','date_ship_success'=>'2020-05-13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'user_id_receiver' => 1, 'user_id' => 2, 'code_deal' => '1000000000001', 'sell_buy' => 1, 'money_value' => 10000000, 'cotpay_fee' => 100000, 'content' => 'Giày', 'wallet_id' => 5, 'phone_receiver' => '0987654322', 'name_sender' => 'Nguyễn thị Chi', 'name_user' => 'Gia dụng shop', 'name_receiver' => 'Nguyễn thị chi', 'address_receiver' => '18 trúc bạch', 'city' => 'Hà Nội', 'district' => 'Sơn Tây', 'ward' =>'Sơn Đông', 'shipping_unit' => 1, 'wide' =>10, 'long' => 10, 'height' => 10, 'collection' =>1, 'service' => 1, 'weight' => 50, 'ship_fee' => 10000, 'status' => 2,'code_bill'=>'-','date_ship_receive'=>'2020-04-13','date_ship_success'=>'2020-05-13','created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'user_id_receiver' => 1, 'user_id' => 2, 'code_deal' => '10000000000021', 'sell_buy' => 1, 'money_value' => 10000000, 'cotpay_fee' => 100000, 'content' => 'Giày', 'wallet_id' => 5, 'phone_receiver' => '0987654322', 'name_sender' => 'Nguyễn thị Chi', 'name_user' => 'Gia dụng shop', 'name_receiver' => 'Nguyễn thị chi', 'address_receiver' => '18 trúc bạch', 'city' => 'Hà Nội', 'district' => 'Sơn Tây', 'ward' =>'Sơn Đông', 'shipping_unit' => 1, 'wide' =>10, 'long' => 10, 'height' => 10, 'collection' =>1, 'service' => 1, 'weight' => 50, 'ship_fee' => 10000, 'status' => 2,'code_bill'=>'-','date_ship_receive'=>'','date_ship_success'=>'','created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'user_id_receiver' => 3, 'user_id' => 2, 'code_deal' => '1000000000002', 'sell_buy' => 1, 'money_value' => 10000000, 'cotpay_fee' => 100000, 'content' => 'Thắt lưng', 'wallet_id' => 5, 'phone_receiver' => '0987654322', 'name_sender' => 'Nguyễn thị Chi', 'name_user' => 'Gia dụng shop', 'name_receiver' => 'Nguyễn thị chi', 'address_receiver' => '18 trúc bạch', 'city' => 'Hà Nội', 'district' => 'Sơn Tây', 'ward' =>'Sơn Đông', 'shipping_unit' => 1, 'wide' =>10, 'long' => 10, 'height' => 10, 'collection' =>1, 'service' => 1, 'weight' => 50, 'ship_fee' => 10000, 'status' => 3,'code_bill'=>'-','date_ship_receive'=>'2020-04-13','date_ship_success'=>'2020-05-13','created_at' => now(), 'updated_at' => now()],

            ['id' => 4, 'user_id_receiver' => 2, 'user_id' => 1, 'code_deal' => '1000000000003', 'sell_buy' => 2, 'money_value' => 10000000, 'cotpay_fee' => 100000, 'content' => 'Quần áo', 'wallet_id' => 5, 'phone_receiver' => '0987654322', 'name_sender' => 'Nguyễn văn Khang', 'name_user' => 'Gia dụng shop', 'name_receiver' => 'Nguyễn thị chi', 'address_receiver' => '18 trúc bạch', 'city' => 'Hà Nội', 'district' => 'Sơn Tây', 'ward' =>'Sơn Đông', 'shipping_unit' => 1, 'wide' =>10, 'long' => 10, 'height' => 10, 'collection' =>1, 'service' => 1, 'weight' => 50, 'ship_fee' => 10000, 'status' => 1,'code_bill'=>'-','date_ship_receive'=>'2020-04-13','date_ship_success'=>'2020-05-13','created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'user_id_receiver' => 2, 'user_id' => 1, 'code_deal' => '1000000000004', 'sell_buy' => 2, 'money_value' => 10000000, 'cotpay_fee' => 100000, 'content' => 'Điện thoại', 'wallet_id' => 5, 'phone_receiver' => '0987654322', 'name_sender' => 'Nguyễn văn Khang', 'name_user' => 'Gia dụng shop', 'name_receiver' => 'Nguyễn thị chi', 'address_receiver' => '18 trúc bạch', 'city' => 'Hà Nội', 'district' => 'Sơn Tây', 'ward' =>'Sơn Đông', 'shipping_unit' => 1, 'wide' =>10, 'long' => 10, 'height' => 10, 'collection' =>1, 'service' => 1, 'weight' => 50, 'ship_fee' => 10000, 'status' => 1,'code_bill'=>'-','date_ship_receive'=>'2020-04-13','date_ship_success'=>'2020-05-13','created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'user_id_receiver' => 2, 'user_id' => 1, 'code_deal' => '1000000000005', 'sell_buy' => 2, 'money_value' => 10000000, 'cotpay_fee' => 100000, 'content' => 'Laptop', 'wallet_id' => 5, 'phone_receiver' => '0987654322', 'name_sender' => 'Nguyễn văn Khang', 'name_user' => 'Gia dụng shop', 'name_receiver' => 'Nguyễn thị chi', 'address_receiver' => '18 trúc bạch', 'city' => 'Hà Nội', 'district' => 'Sơn Tây', 'ward' =>'Sơn Đông', 'shipping_unit' => 1, 'wide' =>10, 'long' => 10, 'height' => 10, 'collection' =>1, 'service' => 1, 'weight' => 50, 'ship_fee' => 10000, 'status' => 1,'code_bill'=>'-','date_ship_receive'=>'2020-04-13','date_ship_success'=>'2020-05-13','created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'user_id_receiver' => 2, 'user_id' => 1, 'code_deal' => '1000000000006', 'sell_buy' => 2, 'money_value' => 10000000, 'cotpay_fee' => 100000, 'content' => 'Tivi', 'wallet_id' => 5, 'phone_receiver' => '0987654322', 'name_sender' => 'Nguyễn văn Khang', 'name_user' => 'Gia dụng shop', 'name_receiver' => 'Nguyễn thị chi', 'address_receiver' => '18 trúc bạch', 'city' => 'Hà Nội', 'district' => 'Sơn Tây', 'ward' =>'Sơn Đông', 'shipping_unit' => 1, 'wide' =>10, 'long' => 10, 'height' => 10, 'collection' =>1, 'service' => 1, 'weight' => 50, 'ship_fee' => 10000, 'status' => 1,'code_bill'=>'-','date_ship_receive'=>'2020-04-13','date_ship_success'=>'2020-05-13','created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
